- name: Catalogue 
  hosts: catalogue
  become: true
  tasks:
  - name: disable nodejs and enable nodejs
    shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: Install NodeJS
    dnf:
     name: nodejs
     state: present
  - name: Create user for roboshop
    user:
     name: roboshop
  - name: Recursively remove app directory
    file:
     path: /app
     state: absent
  - name: Create directory
    file:
     path: /app
     state: directory
  - name: download catalogue application
    get_url: 
     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
     dest: /tmp
  - name: extract catalogue application
    unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes
  - name: Download dependencies
    command: npm install
     args:
      chdir: /app
  - name: Copy catalogue services
    copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service
  - name: deamon realod and start
    systemd_service:
     daemon_reload: true 
 # let's start after the data is loaded
  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
  - name: Install mongodb client
    package:
     name: mongodb-org-shell
     state: present
     


     