- name: Developer has chosen the database MySQL. Hence, we are trying to install it up and configure it.
  hosts: mysql
  become: true
  tasks: 
  - name: Disable mysql
    command: dnf module disable mysql -y
  - name: setup mysql5.7 repo
    copy: 
     src: mysql.repo
     dest: /etc/yum.repos.d/mysql.repo
  - name: Install mysql-community-server 
    package:
     name: mysql-community-server
     state: present
  - name: Start and enable mysql server
    service:
      name: mysqld
      state: started
      enabled: yes
  - name: setup root password
    command: mysql_secure_installation --set-root-pass RoboShop@1
     